language: node_js
sudo: required
node_js:
  - "4.2"

branches:
  only:
    - master
    - stable
    - test

services:
  - redis-server

before_script:
  - psql -c 'create database crypton_test;' -U postgres
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - make

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
